job detail
FPOLY-HCM/WEB3014 pull request #47
Opened 2023-02-13 16:52 UTC by dang-khai

closed #46

2023-02-13 17:10 UTC, datlechin commented on app/Controllers/JobController.php
> +        $company = Job::query(request()->query('id'))->with(['company'])->get();
Chỉ cần 
```suggestion
        $job = Job::query()->with('company')->findOrFail(request()->query('id'));
```

2023-02-14 12:37 UTC, datlechin requested changes

2023-02-14 12:37 UTC, datlechin commented on app/views/jobs/show.php
> +                            <div class="sidebar-text-info ml-10"><span class="text-description jobtype-icon mb-10">Ngày cập nhật</span><strong class="small-heading"><?php echo explode(" ", $job->upda
Không sài `echo` keyword trong file view

```suggestion
                            <div class="sidebar-text-info ml-10"><span class="text-description jobtype-icon mb-10">Ngày cập nhật</span><strong class="small-heading"><?= $job->updated-at->format('d/m/Y') ?></strong></div>
```

2023-02-14 12:37 UTC, datlechin commented on app/views/jobs/show.php
> +                    <h4>Kiến thức, kỹ năng và kinh nghiệm thiết yếu</h4>
toàn bộ content trong class `content-single` là `$job->content`

2023-02-14 16:56 UTC, datlechin commented on app/views/jobs/show.php
>                      <ul>
nội dung bên trong div `content-single` là `$job->content`

2023-02-14 16:58 UTC, dang-khai commented on app/views/jobs/show.php
>                      <ul>
là chỉ cần 1 thẻ <p><?= $job->content ?> trong content-single thôi hả

2023-02-14 17:03 UTC, datlechin commented on app/views/jobs/show.php
>                      <ul>
chứ chẳng lẻ lặp lại `$job->content` trăm lần?

2023-02-14 17:36 UTC, datlechin commented on app/views/jobs/show.php
> +                    <h4>Chào mừng đến với <?= $job->company->name ?></h4>
Vẫn chưa đạt

2023-02-15 05:53 UTC, datlechin commented on app/views/jobs/show.php
> +                    <p><?= $job->content ?>.</p>
Vẫn chưa đạt
Còn dư thẻ p

2023-02-15 12:35 UTC, datlechin approved these changes

2023-02-15 12:36 UTC, merged