flash_message
FPOLY-HCM/WEB3014 pull request #62
Opened 2023-02-20 06:20 UTC by dang-khai

closed #61

2023-02-20 06:21 UTC, datlechin commented on app/Controllers/Account/ApplicationController.php
> +        return redirect('/account/applications', compact(flash()->add('Thêm thành công', 'success')));
sao lại compact flash ?

làm giống bên logincontroller

2023-02-20 12:47 UTC, datlechin commented
Chưa hiển thị message ngoài view

2023-02-20 13:27 UTC, dang-khai commented
> Chưa hiển thị message ngoài view

có r mà commit trên á

2023-02-21 00:16 UTC, datlechin commented
Chỉ mới các trường hợp success
Còn các trường hợp lỗi như validate

2023-02-22 13:39 UTC, datlechin requested changes

2023-02-22 13:39 UTC, datlechin commented on app/Controllers/Account/ApplicationController.php
> +        if (! request()->has('job_id')) {
chưa check account đã đăng nhập hay chưa

2023-02-22 14:29 UTC, datlechin approved these changes

2023-02-22 14:29 UTC, merged